### ISSUE TITLE
Kit-stretching ideas (actions)

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#1001]
This is an issue for ideas that could be implemented into pgm in the form of kits, even though they really stretch the definition of what *kit* is supposed to mean. The new terminology they'll adopt is *triggers*, which can be found over at #1016 .

Keep in mind, that not all of these must be viable to implement, or make sense to implement. It's just a list of anything that *could maybe be looked at*, some may become impractical or non viable upon closer inspection or when trying to look at details of implementation.

The ideas/brainstorming for future kits:
 - [x] variable-related kits (see #881)
 - [x] `text` - sends a text message to the player #900
 - [x] `sound` - plays a certain sound for the player #1216
 - [ ] `pickup-flag`, `drop-flag` - makes the player pick-up or drop the flag #930
 - [ ] `match-end` - ends the match, optionally:  tie, player wins, specific team wins, or default to a victory condition (like time-limit)
 - [x] `timelimit` - add or subtract a certain amount of time from the match time limit
 - [x] `score` - award score, (could even replace scoreboxes?)
 - [x] `teleport` - teleport the player, (could even replace portals?)
 - [ ] `capture`, `uncapture` - modify control points' ownership #942
 
 Feel free to suggest more ideas for kits-that-aren't-really-kits

**Comment by KingOfSquares** [comment]
Didn't avicus use something called executors or something? Could be a viable alternative to stuff not belonging under the kit term.

**Comment by lefckntea** [comment]
can i make tnt tag (flag tag?) with pickup-flag and drop-flag? or does it need more stuff like the transfer flag when hitting someone idea ruediger had in the issue mentioned 

they‘d also needa go boom then for the tnt tag mechanic
