### ISSUE TITLE
Tracking modern support lacking features

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#1332]
Most if not all PGM features have been reimplemented in the newer features, with some exceptions:
 - [x] CanPlaceOn/CanBreak: Fixed in #1394 
   -  ~~Removed in 1.20.6 spigot/paper due to changes in vanilla.~~
   -  ~~Hoping to add them back when they re-add them in 1.21 or something.~~
 - [x] Knockback reduction kit Fixed in #1448 
   - This relied on a sportpaper only patch to set a multiplier to the kb taken
   - Got it replaced with a knockback resistance attribute, since that's what it does in newer versions (in older versions it was a % chance of receiving 0 kb, instead of a multiplier on kb taken)
 - [ ] Extra data in ping packet #1532 
   - This was also a sportpaper exclusive, we can't freely modify the ping packet to add extra data in paper
 - [x] Observers seeing invisible players #1450 
   - sportpaper exclusive. Obs will not be able to see invisible players. 
   - Maybe can get this back by modifying packets in protocol lib.
 - [x] Hide all potion particles for players #1449 
   - sportpaper feature that PGM enabled by default on all kits who didn't explicitly disable it, only ghost squadron really disabled it.
   - Got this fully back by modifying packets in protocol lib
 - [x] Can't track entities spawned by dispensers (BlockDispenseEntityEvent) #1451
   - If the spawned entity (arrow, spawn egg, tnt, etc) deals damage to someone, it doesn't count as yours for having placed the dispenser
   - This is likely very hard to work around, if at all possible
 - [x] Can't track who caused an explosion (eg: tnt or creeper) (ExplosionPrimeByEntityEvent) #1451
   - When you shoot a tnt with flame, or light a creeper with flint & steep, it can't count that explosion as yours
   - When a TNT you lit, makes another tnt go off, it can't count it as yours either
   - This is likely very hard to work around, if at all possible
 - [ ] EntityExtinguishEvent is missing, this should only be an internal technical issue as certain state doesn't get cleaned up, but shouldn't see feature differences.

**Comment by Brottweiler** [comment]
I hope these are relevant to this issue:

- [x] The icons in the settings menu are all ink sacs, probably because they use damage values but are now items.
- [x] `potion duration="oo"` should probably be made into actual `infinite` duration. [[ref](https://minecraft.wiki/w/Commands/effect#Syntax)]
- [x] Maps previously on level 0 are no longer at the void, consider adding a setting similar to `maxbuildheight` that determines the lowest possible build limit.
- [x] Auto-learn all recipes (make sure to disable all advancements in `spigot.yml`.

**Comment by Mew2K** [comment]
- [x] InventoryClickEvent out of bounds
  - On CTW maps, attempting to double-left-click on the wool inside of a wool-chest causes an InventoryClickEvent error, and leads to all but one piece of wool to simply vanish

```
[14:15:03 ERROR]: Could not pass event InventoryClickEvent to PGM v0.16-SNAPSHOT (git-ef6195a)
java.lang.IndexOutOfBoundsException: Index 90 out of bounds for length 90
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
        at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at net.minecraft.core.NonNullList.get(NonNullList.java:44) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.world.inventory.AbstractContainerMenu.getSlot(AbstractContainerMenu.java:375) ~[paper-1.21.jar:1.21-83-967f98a]
        at org.bukkit.craftbukkit.inventory.CraftInventoryView.getItem(CraftInventoryView.java:73) ~[paper-1.21.jar:1.21-83-967f98a]
        at PGM-0.16-SNAPSHOT-ef6195a.jar/tc.oc.pgm.util.listener.ItemTransferListener.onPlayerInventoryClick(ItemTransferListener.java:510) ~[PGM-0.16-SNAPSHOT-ef6195a.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor30.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-83-967f98a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-83-967f98a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-83-967f98a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3122) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1533) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1510) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1503) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1462) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1469) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1314) ~[paper-1.21.jar:1.21-83-967f98a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-83-967f98a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
https://github.com/user-attachments/assets/c5ecd21c-77ce-401b-bb86-834f414d8ca5

**Comment by Pablete1234** [comment]
> * InventoryClickEvent
>   
>   * On CTW maps, attempting to double-left-click on the wool inside of a wool-chest causes all but one piece of wool to simply vanish, and results in an InventoryClickEvent error in the console.
>   * This only seems to happen when you do it on the original wool in the chest (in other words, if I went into creative mode, manually filled the chest back up with wool, and performed the double-left-click again, no errors would occur).
> 
>  Minecraft.1.21.-.Multiplayer.3rd-party.Server.2024-07-17.14-14-59.mp4

please provide the stacktrace of the error in console when there is one

**Comment by Brottweiler** [comment]
_Adding this old issue from a discord message since I don't think it's tracked anywhere._

On Snowy Wars on 1.21, you get resistance in spawn rooms that should go away when you leave spawn but it doesn't.

https://github.com/OvercastCommunity/PublicMaps/blob/main/dtcm/snowy_wars/map.xml#L55
https://github.com/OvercastCommunity/PublicMaps/blob/main/dtcm/snowy_wars/map.xml#L117

**Comment by Brottweiler** [comment]
Also posting this here since it probably only affects modern.

```
[19:20:47 ERROR]: [PGM] [STDERR] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[19:20:47 WARN]: Nag author(s): '[]' of 'PGM v0.16-SNAPSHOT (git-81fcde56)' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[19:20:47 ERROR]: [PGM] [STDERR] SLF4J: Defaulting to no-operation (NOP) logger implementation
[19:20:47 ERROR]: [PGM] [STDERR] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[19:20:50 WARN]: [PGM] "PGM v0.16-SNAPSHOT (git-81fcde56)" has registered a listener for org.bukkit.event.entity.EntityRemoveEvent on method "public void tc.oc.pgm.platform.modern.ModernListener.onEntityDespawn(org.bukkit.event.entity.EntityRemoveEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].
```

**Comment by Pablete1234** [comment]
> Also posting this here since it probably only affects modern.
> 
> ```
> [19:20:47 ERROR]: [PGM] [STDERR] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> [19:20:47 WARN]: Nag author(s): '[]' of 'PGM v0.16-SNAPSHOT (git-81fcde56)' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
> [19:20:47 ERROR]: [PGM] [STDERR] SLF4J: Defaulting to no-operation (NOP) logger implementation
> [19:20:47 ERROR]: [PGM] [STDERR] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> [19:20:50 WARN]: [PGM] "PGM v0.16-SNAPSHOT (git-81fcde56)" has registered a listener for org.bukkit.event.entity.EntityRemoveEvent on method "public void tc.oc.pgm.platform.modern.ModernListener.onEntityDespawn(org.bukkit.event.entity.EntityRemoveEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].
> ```

I believe none of these can be fixed at the moment.

- PGM uses custom logging that gets the "usage of system.out"
- The event is a generic warning for using any deprecated event, in this case it will *not* have a performance problem and paper does not provide an API that can provide an alternative for it, yet.

**Comment by Pablete1234** [comment]
> _Adding this old issue from a discord message since I don't think it's tracked anywhere._
> 
> On Snowy Wars on 1.21, you get resistance in spawn rooms that should go away when you leave spawn but it doesn't.
> 
> https://github.com/OvercastCommunity/PublicMaps/blob/main/dtcm/snowy_wars/map.xml#L55 https://github.com/OvercastCommunity/PublicMaps/blob/main/dtcm/snowy_wars/map.xml#L117

Apparently `force` does nothing on modern (and the method with that `force` option is deprecated). And the rationale seems to be:
![image](https://github.com/user-attachments/assets/dd409a3c-03bd-43f0-bfb3-f3c1dfb88b65)

I've added a workaround in pgm where a force kit with duration=0 effects will clear instead of giving the effect. see #1441
